<?php
/**
 * Configuration file generated by ZF Apigility Admin
 *
 * The previous config file has been stored in ./config/modules.config.old
 */
return [
    'Zend\Cache',
    'Zend\Form',
    'Zend\\Db',
    'Zend\\Filter',
    'Zend\\Hydrator',
    'Zend\\InputFilter',
    'Zend\\Paginator',
    'Zend\\Router',
    'Zend\\Validator',
    'ZF\\Apigility',
    'ZF\\Apigility\\Documentation',
    'ZF\Apigility\Documentation\Swagger',
    'ZF\\ApiProblem',
    'ZF\\Configuration',
    'ZF\\Hal',
    'ZF\\ContentNegotiation',
    'ZF\\ContentValidation',
    'ZF\\Rest',
    'ZF\\Rpc',
    'ZF\\Versioning',
    'DoctrineModule',
    'Phpro\DoctrineHydrationModule',
    'ZF\Apigility\Doctrine\Server',
    'DoctrineORMModule',
    'ZF\Apigility\Documentation\Swagger',
    'Application',
    'Dados',
];
