<?= $this->doctype() ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <!-- Bootstrap4 -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<?php
echo $this->headTitle('Apigility');

echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');

echo $this->headLink(['rel' => 'icon', 'type' => 'image/png', 'href' => $this->basePath('/img/favicon.png')])
    ->prependStylesheet($this->basePath('/zf-apigility/css/main.min.css'))
    ->prependStylesheet($this->basePath('/zf-apigility/css/bootstrap.min.css'));

echo $this->headScript()
    ->prependFile($this->basePath('/zf-apigility/js/bootstrap.min.js'))
    ->prependFile($this->basePath('/zf-apigility/js/jquery.min.js'));
?>
</head>
<body>
    <div class="container">
        <?= $this->content ?>
    </div>
    <footer>
        <hr>
        <div class="container center-block"><div class="row">
            <div class="col-sm-4">
                &copy; Copyright 2019 - <?= date('Y') ?>
                by <a href="#">Data Unity</a> Ltd.
            </div>
        </div></div>
    </footer>
    <?= $this->inlineScript() ?>
</body>
</html>
